language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
  - '10'
  - '8'
script:
  npm run test:prod && npm run build
  npm run test-coverage-report
after_success:
  - npm run test-coverage-report
  - npm run semantic-release
branches:
  only:
    - master
